### ISSUE TITLE
lacking autoload.php as per opis/closure

### ISSUE THREAD

**Issue by joejoseph00** [opis/stream#1]
The opis/closure has an autoload.php , I am testing out opis/stream however it does not have an autoload.php

I attempted to create one myself based on the autoload.php in the opis/closure project however it did not pick up the Opis\Wrapper class I'm trying to use.

when I run this code:
`\Opis\Stream\Wrapper\PHPCodeStreamWrapper::include('<?php return function(' . $args . ') {' . $code. '};')`

I get:

`Error: Class 'Opis\Stream\Wrapper\PHPCodeStreamWrapper' not found`

**Comment by joejoseph00** [comment]
this is spun from https://github.com/opis/closure/pull/38

**Comment by sorinsarca** [comment]
It doesn't need an autoload if you use composer.

Here is an example of autoloader

```php
<?php
spl_autoload_register(function($class){
    $class = ltrim($class, '\\');
    $dir = __DIR__ . '/src';
    $namespace = 'Opis\Stream';
    if(strpos($class, $namespace) === 0)
    {
        $class = substr($class, strlen($namespace));
        $path = '';
        if(($pos = strripos($class, '\\')) !== FALSE)
        {
            $path = str_replace('\\', '/', substr($class, 0, $pos)) . '/';
            $class = substr($class, $pos + 1);
        }
        $path .= str_replace('_', '/', $class) . '.php';
        $dir .= '/' . $path;
        if(file_exists($dir))
        {
            include $dir;
            return true;
        }
        return false;
    }
    return false;
});
```

**Comment by joejoseph00** [comment]
Thanks, I did end up getting that autoloader.php to work properly

however this approach caused a fatal Drupal core error as follows:

`Exception: Serialization of 'Closure' is not allowed in serialize() (line 465 of web/includes/cache.inc).`


So therefore I am recommending my forked closure library that relies on the file_exists validation and validation for nulls.

https://github.com/entreprise7pro/closure

**Comment by joejoseph00** [comment]
essentially the failed stream approach is this:

```
 function views_php_create_function($args, $code) {
  $version = phpversion();
  $version = explode('.', $version);
  $phpver = ($version[0] * 10000 + $version[1] * 1000);
  if ($phpver >= 72000) {
    libraries_load('stream');
    return \Opis\Stream\Wrapper\PHPCodeStreamWrapper::include('<?php return function(' . $args . ') {' . $code. '};');
  } else {
    return create_function($args, $code);
  }
 }

```

**Comment by joejoseph00** [comment]
attempted to handle only php 7.2.0 or higher and otherwise use the create_function() which we know works.

the stream approach resulted in:

`Exception: Serialization of 'Closure' is not allowed in serialize() (line 465 of web/includes/cache.inc).`

**Comment by sorinsarca** [comment]
That has nothing to do with opis/stream, you want to serialize a closure so use opis/closure,
since opis/closure 3.4.0 you don't need opis/stream to create plain closures.

**Comment by joejoseph00** [comment]
ok, I'll try that suggestion thanks

**Comment by joejoseph00** [comment]
yes I tried that suggestion also and reported the results here: https://github.com/opis/closure/pull/38
